name: Pass eslint
on: [pull_request]

jobs:
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
        - name: Installation
            run: yarn install --ignore-scripts
        - name: Try Linting
            run: yarn lint